version: "3"
services:
  eduroom_frontend:
    build:
      context: ./eduroom_frontend
      dockerfile: Dockerfile.dev
    depends_on:
      - eduroom_backend
    volumes:
      - ./eduroom_frontend:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/.next
    environment:
      - BACKEND_API=http://eduroom_backend:5000
    ports:
      - "3000:3000"
  nginx:
    restart: always
    depends_on:
      - eduroom_frontend
      - eduroom_backend
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - "80:80"

  eduroom_backend:
    build:
      dockerfile: Dockerfile.dev
      context: ./eduroom_backend
    volumes:
      - /usr/src/app/node_modules
      - ./eduroom_backend:/usr/src/app
    depends_on:
      - eduroom_postgres
    environment:
      - WAIT_HOSTS=eduroom_postgres:5432
      - NODE_ENV=development
      - PORT=5000
      - CLIENT_URL=http://localhost:3000
      - DB_USER=eduroom_user
      - DB_PASSWORD=213456
      - DB_HOST=eduroom_postgres
      - DB_PORT=5432
      - DB_NAME=eduroom_db
      - GOOGLE_CLIENT_ID=915718814816-au5njmbt31b0g4lctg8edqm3rs53vvcn.apps.googleusercontent.com
      - GOOGLE_SECRET_KEY=dDwssvp5-CCfvXs7vhlNhxIi
    ports:
      - "5000:5000"

  eduroom_postgres:
    image: "postgres:12"
    environment:
      - POSTGRES_USER=eduroom_user
      - POSTGRES_PASSWORD=213456
      - POSTGRES_DB=eduroom_db
    volumes:
      - database-data:/var/lib/postgresql/data/
      - ./eduroom_backend/src/database/database.sql:/docker-entrypoint-initdb.d/database.sql
    ports:
      - "5432:5432"
volumes:
  database-data: 