version: "3"
services:
  eduroom_frontend:
    build:
      context: ./eduroom_frontend
      dockerfile: Dockerfile.dev
    depends_on:
      - eduroom_backend
    volumes:
      - ./eduroom_frontend:/usr/src/app
      - /usr/src/app/node_modules
      -  ./eduroom_frontend/.next:/usr/src/app/.next
    environment:
      - BACKEND_API=http://eduroom_backend:5000
      - GRADER_URL=http://eduroom_grading_server:3050
      - CHAT_SERVER=http://eduroom_socket_chat:5050
      - KAHOOT_URL=http://eduroom_socket_kahoot:8000
    ports:
      - "3000:3000"
  nginx:
    restart: always
    depends_on:
      - eduroom_frontend
      - eduroom_backend
      - eduroom_grading_server
      - eduroom_socket_chat
      - eduroom_socket_kahoot
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - "80:80"

  eduroom_backend:
    build:
      dockerfile: Dockerfile.dev
      context: ./eduroom_backend
    volumes:
      - /usr/src/app/node_modules
      - ./eduroom_backend:/usr/src/app
    depends_on:
      - eduroom_postgres
    environment:
      - WAIT_HOSTS=eduroom_postgres:5432
      - NODE_ENV=development
      - PORT=5000
      - CLIENT_URL=http://localhost:3000
      - BACKEND_API=http://localhost:5000
      - DB_USER=eduroom_user
      - DB_PASSWORD=213456
      - DB_HOST=eduroom_postgres
      - DB_PORT=5432
      - DB_NAME=eduroom_db
      - JWT_SECRET=jwtsecret
      - JWT_EXPIRE=30d
      - JWT_COOKIE_EXPIRE=30
      - GOOGLE_CLIENT_ID=915718814816-au5njmbt31b0g4lctg8edqm3rs53vvcn.apps.googleusercontent.com
      - GOOGLE_SECRET_KEY=dDwssvp5-CCfvXs7vhlNhxIi
      - SMTP_SECURE=false
      - SMTP_HOST=eduroom_smtp
      - SMTP_PORT=1025
      - SMTP_EMAIL=
      - SMTP_PASSWORD=
      - FROM_EMAIL=admin@eduroom.com
      - FROM_NAME=Eduroom Admin
      - NODE_TLS_REJECT_UNAUTHORIZED=0
    ports:
      - "5000:5000"
  eduroom_grading_server:
    build:
      dockerfile: Dockerfile.dev
      context: ./eduroom_grading_server
    volumes:
      - /usr/src/app/node_modules
      - ./eduroom_grading_server:/usr/src/app
    environment:
      - NODE_ENV=development
      - PORT=3050
      - CLIENT_URL=http://localhost:3000
    ports:
      - "3050:3050"
  eduroom_socket_chat:
    build:
      dockerfile: Dockerfile.dev
      context: ./eduroom_socket_chat
    volumes:
      - /usr/src/app/node_modules
      - ./eduroom_socket_chat:/usr/src/app
    environment:
      - NODE_ENV=development
      - PORT=5050
      - CLIENT_URL=http://localhost:3000
    ports:
      - "5050:5050"
  eduroom_socket_kahoot:
    build:
      dockerfile: Dockerfile.dev
      context: ./eduroom_socket_kahoot
    volumes:
      - /usr/src/app/node_modules
      - ./eduroom_socket_kahoot:/usr/src/app
    environment:
      - NODE_ENV=development
      - PORT=8000
      - CLIENT_URL=http://localhost:3000
    ports:
      - "8000:8000"
  eduroom_postgres:
    image: "postgres:12"
    environment:
      - POSTGRES_USER=eduroom_user
      - POSTGRES_PASSWORD=213456
      - POSTGRES_DB=eduroom_db
    volumes:
      - database-data:/var/lib/postgresql/data/
      - ./eduroom_backend/src/database/database.sql:/docker-entrypoint-initdb.d/database.sql
    ports:
      - "5432:5432"
  eduroom_smtp:
    image: reachfive/fake-smtp-server
    ports:
      - "1025:1025"
      - "1080:1080"
volumes:
  database-data: 
