apiVersion: apps/v1
kind: Deployment
metadata:
  name: eduroom-socket-chat-deployment
spec:
  selector:
    matchLabels:
      app: eduroom-socket-chat-deployment
  template:
    metadata:
      labels:
        app: eduroom-socket-chat-deployment
    spec:
      containers:
      - name: eduroom-socket-chat-deployment
        image: asia.gcr.io/macbigduck/eduroom-socket-chat
        # resources:
        #   limits:
        #     memory: "128Mi"
        #     cpu: "500m"
        ports:
        - containerPort: 5050
        env:
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: prod-configmap
                  key: NODE_ENV
            - name: CLIENT_URL
              valueFrom:
                configMapKeyRef:
                  name: prod-configmap
                  key: CLIENT_URL
                  optional: false
