apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    kubernetes.io/ingress.class: nginx
    # nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  # tls:
  #   - hosts:
  #     - cs21.cscms.me
  #     secretName: cs21-cf
  #   - hosts:
  #     - cs21socket.cscms.me
  #     secretName: cs21-socket-cf
  rules:
    - http:
        paths:
          - path: /socket-chat
            backend:
              serviceName: eduroom-socket-chat-clusterip
              servicePort: 5050
          - path: /kahoot
            backend:
              serviceName: eduroom-socket-kahoot-clusterip
              servicePort: 8000
          - path: /grader
            backend:
              serviceName: eduroom-grading-server-clusterip
              servicePort: 3050
          - path: /api
            backend:
              serviceName: eduroom-backend-clusterip
              servicePort: 5000
          - path: /
            backend:
              serviceName: eduroom-frontend-clusterip
              servicePort: 3000