apiVersion: v1
kind: ConfigMap
metadata:
  name: prod-configmap
data:
  # Frontend 
  BACKEND_API: eduroom-backend-clusterip:5000
  CLIENT_URL: eduroom-frontend-clusterip:3000
  GRADER_URL: eduroom-grading-server-clusterip:3050
  CHAT_SERVER: eduroom-socket-chat-clusterip:5050
  KAHOOT_URL: eduroom-socket-kahoot-clusterip:8000
  # DB
  POSTGRES_PORT: "5432"
  # Backend
  NODE_ENV: production
  WAIT_HOSTS: 127.0.0.1:5432
  JWT_SECRET: jwtsecret
  JWT_EXPIRE: 30d
  JWT_COOKIE_EXPIRE: "30"