apiVersion: v1
kind: ConfigMap
metadata:
  name: prod-configmap
data:
  # Frontend 
  BACKEND_API: https://eduroom.cscms.me/api
  CLIENT_URL: https://eduroom.cscms.me
  GRADER_URL: https://eduroom.cscms.me/grader
  CHAT_SERVER: https://eduroom.cscms.me/socket-chat # Path option is seted
  KAHOOT_URL: https://eduroom.cscms.me # Path option is seted
  # DB
  POSTGRES_PORT: "5432"
  # Backend
  NODE_ENV: production
  WAIT_HOSTS: 127.0.0.1:5432
  JWT_EXPIRE: 30d
  JWT_COOKIE_EXPIRE: "30"
  GCS_SA_KEY_PATH: /etc/secret/gcs
  SMTP_SECURE: "true"
  FROM_EMAIL: no-reply@eduroom.cscms.me
  FROM_NAME: Eduroom