name: Pull Request Building

on:
#   pull_request:
#     branches: 
#       - dev
#       - master
  push:
    branches: 
      - supertest
env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: eduroom-cluster
  GKE_ZONE: asia-southeast1-b

jobs:
  setup-build-test:
    name: Setup and Build Frontend
    runs-on: [self-hosted, linux, x64]
    env:
      DOCKER_BUILDKIT: '1'
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    # Setup gcloud CLI
#     - uses: GoogleCloudPlatform/github-actions/setup-gcloud@0.1.3
#       with:
#         service_account_key: ${{ secrets.GKE_SA_KEY }}
#         project_id: ${{ secrets.GKE_PROJECT }}

    # Configure Docker to use the gcloud command-line tool as a credential
    # helper for authentication
#     - run: |-
#         gcloud --quiet auth configure-docker
        
#     - name: Build Eduroom Frontend Image
#       run: |-
#         docker build -f eduroom_frontend/Dockerfile \
#           --tag "asia.gcr.io/$PROJECT_ID/eduroom-frontend:$GITHUB_SHA" \
#           --build-arg GITHUB_SHA="$GITHUB_SHA" \
#           --build-arg GITHUB_REF="$GITHUB_REF" \
#           --build-arg BUILDKIT_INLINE_CACHE=1 \
#           --cache-from "asia.gcr.io/$PROJECT_ID/eduroom-frontend" \
#           eduroom_frontend
          
    - name: Build, Test Eduroom Backend Image
      run: docker-compose -f docker-compose.test.yml run eduroom_backend
